# -*- coding: utf-8 -*-
"""AbstractiveTextSummarization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UjxWxwfg7lVTSraP_2Yxohex_dm8O14Q

# Abstractive Text Summarization with T5 (GPT-like Model)

This notebook demonstrates abstractive text summarization using a pre-trained T5 model from the Hugging Face Transformers library. T5 (Text-to-Text Transfer Transformer) is a powerful encoder-decoder model that can perform various text-to-text tasks, including summarization, making it a great choice for 'GPT-like' abstractive summarization.

### 1. Install Necessary Libraries
"""

!pip install transformers

"""### 2. Load the Pre-trained Model and Tokenizer"""

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_name = "t5-small"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

def summarizer(text, max_length=150, min_length=30, do_sample=False):
    inputs = tokenizer(
        "summarize: " + text,
        return_tensors="pt",
        max_length=512,
        truncation=True
    )
    summary_ids = model.generate(
        inputs["input_ids"],
        attention_mask=inputs["attention_mask"],
        max_length=max_length,
        min_length=min_length,
        do_sample=do_sample,
        num_beams=4,
        early_stopping=True
    )
    return [
        {
            "summary_text": tokenizer.decode(summary_ids[0], skip_special_tokens=True)
        }
    ]

print("T5 summarization model loaded successfully!")

"""### 3. Prepare Input Text

### 3.1 Load Input Text from a Dataset
"""

!pip install datasets

from datasets import load_dataset

dataset = load_dataset("cnn_dailymail", '3.0.0', split='test')

article_index = 11
dataset_article = dataset[article_index]['article']

input_text = dataset_article

print(f"Loaded article from cnn_dailymail dataset (index {article_index}).")
print("Original Text (first 500 chars):\n", input_text[:500] + "...")

# This cell previously contained a static example text that was overwriting the dataset input.
# It has been cleared to ensure the summarization uses the article from the cnn_dailymail dataset.

"""The `input_text` variable is now intended to be updated with an article from the `cnn_dailymail` dataset. To ensure you are using the dataset article for summarization, please **re-run cell `74ad84da`** (the code that loads the dataset article) and then **re-run cell `2b1a871c`** (the code that generates the summary).

### 4. Generate the Summary
"""

summary_list = summarizer(input_text, max_length=150, min_length=30, do_sample=False)

abstractive_summary = summary_list[0]['summary_text']

print("\nAbstractive Summary:\n", abstractive_summary)

"""### 5. Conclusion

This example demonstrates the basic steps for performing abstractive text summarization. For more advanced use cases, you might want to:

*   **Use a larger model:** `t5-base`, `t5-large`, `facebook/bart-large-cnn`, or `google/pegasus-xsum` for better quality summaries.
*   **Fine-tune the model:** Train the model on your specific dataset for domain-specific summarization.
*   **Adjust summarization parameters:** Experiment with `max_length`, `min_length`, `do_sample`, `num_beams`, etc., to control the summary length and style.

## README: Abstractive Text Summarization with T5

This notebook provides a practical demonstration of abstractive text summarization using a pre-trained T5 model from the Hugging Face Transformers library.

### 1. Introduction to Abstractive Summarization

Abstractive summarization is a natural language processing (NLP) task where the model generates new sentences that capture the most important information from the source text, rather than simply extracting existing sentences (extractive summarization). This approach allows for more human-like, concise, and nuanced summaries, often paraphrasing the original content.

### 2. The Transformers Library

The Hugging Face `transformers` library is an open-source library that provides thousands of pre-trained models for various NLP tasks, including text classification, question answering, translation, and summarization. It offers a unified API for accessing and using these models across different frameworks (PyTorch, TensorFlow, JAX), making it a popular choice for both research and production.

### 3. T5 (Text-to-Text Transfer Transformer) Model

T5, or Text-to-Text Transfer Transformer, is a powerful encoder-decoder model developed by Google. Its key innovation is framing every NLP problem as a "text-to-text" problem, where the input is text and the output is also text. For summarization, this means providing an input like "summarize: [your text]" and getting a summarized text as output. The `t5-small` model is used in this notebook for demonstration due to its smaller size and faster inference, though larger models (`t5-base`, `t5-large`) offer higher quality summaries.

### 4. CNN/DailyMail Dataset

The `cnn_dailymail` dataset is a widely used benchmark dataset for the task of text summarization. It consists of news articles from CNN and Daily Mail, paired with human-written summaries (highlights). This dataset is instrumental in training and evaluating abstractive summarization models. In this notebook, we load an article from the test split of this dataset to showcase the summarization process.

### 5. Summarization Process

The summarization process in this notebook involves the following steps:

1.  **Installation of Libraries**: Installing `transformers` and `datasets` via `pip`.
2.  **Model and Tokenizer Loading**: Loading the `AutoTokenizer` and `AutoModelForSeq2SeqLM` for the `t5-small` model. The tokenizer converts text into numerical tokens that the model can understand, and the model performs the actual sequence-to-sequence generation.
3.  **Custom Summarizer Function**: A custom `summarizer` function is defined to encapsulate the tokenization, model inference, and decoding steps. This function prepares the input text with the "summarize:" prefix, generates summary IDs using beam search, and decodes them back into human-readable text.
4.  **Input Text Preparation**: An article is loaded from the `cnn_dailymail` dataset to serve as the input for summarization. This demonstrates how to integrate external datasets with the model.
5.  **Summary Generation**: The `summarizer` function is called with the prepared input text and configurable parameters such as `max_length`, `min_length`, and `do_sample` to control the output summary's characteristics.
6.  **Output**: The generated abstractive summary is printed, demonstrating the model's ability to condense the original article into a concise new text.

### 6. Further Improvements

For more advanced use cases or improved performance, consider the following:

*   **Larger Models**: Experiment with `t5-base`, `t5-large`, `facebook/bart-large-cnn`, or `google/pegasus-xsum` for higher quality summaries.
*   **Fine-tuning**: Fine-tune the chosen model on a domain-specific dataset to achieve better summarization tailored to your particular needs.
*   **Parameter Tuning**: Adjust the summarization parameters (`max_length`, `min_length`, `do_sample`, `num_beams`, `early_stopping`) to optimize the length, coherence, and style of the generated summaries.
"""